services:
  db:
    image: postgres:15
    container_name: postgres_gorm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sandbox_lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./docker_data/minio:/data
    command: server /data --console-address ":9001"
